### ISSUE TITLE
Store uploaded podcasts

### ISSUE THREAD

**Issue by Prescientje** [Prescientje/react-podcaster-api#2]

**Comment by pastorsj** [comment]
## Acceptance Criteria
* An endpoint for getting a podcast by id
* An endpoint for updating a podcast
* An endpoint for uploading podcast information (should be done before uploading the file)
* An endpoint for uploading a podcast file
* AWS S3 instance setup and functioning
* Endpoints for creating, uploading, and updating podcasts should be secure by JWTs and other access checks
